version: '3'

services:
  database:
    image: 'postgres:alpine'
    environment:
      POSTGRES_PASSWORD: main
      POSTGRES_USER: main
      POSTGRES_DB: main
    ports:
      - "49186:5432"
  php:
    container_name: php8
    build:
      context: ./docker/php-fpm
    ports:
      - '9000:9000'
    volumes:
      - ./:/var/www/api
      - ./.env:/var/www/api/.env.local
    depends_on:
      - database
    tty: true
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '8008:80'
    volumes:
      - ./:/var/www/api
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database
